-- Migration 131: Seed graph entities from frontend/src/data/graph-entities.js
-- Includes: graph_funds, people, externals, accelerators, ecosystem_orgs, listings
-- Uses ON CONFLICT DO NOTHING to avoid overwriting enrichment data
-- Generated: 2026-03-30

BEGIN;

-- ── Graph Funds ────────────────────────────────────────────────────────────
INSERT INTO graph_funds (id, name, fund_type) VALUES
  ('bbv', 'Battle Born Venture', 'SSBCI'),
  ('fundnv', 'FundNV', 'SSBCI'),
  ('1864', '1864 Fund', 'SSBCI'),
  ('sbir', 'SBIR/STTR', 'Federal'),
  ('angelnv', 'AngelNV', 'Angel'),
  ('sierra', 'Sierra Angels', 'Angel')
ON CONFLICT (id) DO NOTHING;

-- ── People ─────────────────────────────────────────────────────────────────
INSERT INTO people (id, name, role, company_id, note) VALUES
  ('p_straubel', 'JB Straubel', 'Founder/CEO', 1, 'Tesla co-founder'),
  ('p_reynolds', 'Ryan Reynolds', 'CCO', 9, 'Chief Creative Officer'),
  ('p_kurtzer', 'Gregory Kurtzer', 'Founder', 11, 'CentOS/Rocky Linux creator'),
  ('p_barron', 'Maryssa Barron', 'Founder/CEO', 63, 'AngelNV 2025 winner'),
  ('p_tomasik', 'Piotr Tomasik', 'Founder', 4, 'AMD GPU cloud pioneer'),
  ('p_saling', 'Jeff Saling', 'Exec Director', NULL, 'StartUpNV co-founder, FundNV GP')
ON CONFLICT (id) DO NOTHING;

-- ── Externals ──────────────────────────────────────────────────────────────
INSERT INTO externals (id, name, entity_type, note) VALUES
  ('x_stellantis', 'Stellantis', 'Corporation', 'Lyten strategic investor'),
  ('x_fedex', 'FedEx', 'Corporation', 'Lyten strategic investor'),
  ('x_honeywell', 'Honeywell', 'Corporation', 'Lyten strategic investor'),
  ('x_okapi', 'Okapi VC', 'VC Firm', 'MagicDoor seed co-lead'),
  ('x_shadow', 'Shadow Ventures', 'VC Firm', 'MagicDoor seed co-lead'),
  ('x_stripes', 'Stripes', 'VC Firm', 'Katalyst Series A lead'),
  ('x_doe', 'US Dept of Energy', 'Government', '$2B Redwood loan; $996M Ioneer loan; $350M Ormat loan; Aqua Metals grant. Loan Programs Office.'),
  ('x_nasa', 'NASA', 'Government', 'SNC Dream Chaser contract'),
  ('x_fda', 'FDA', 'Government', 'Katalyst; Filament Health'),
  ('x_snwa', 'SNWA', 'Government', 'WaterStart backer'),
  ('x_digitalbridge', 'DigitalBridge', 'PE Firm', 'Took Switch Inc private 2022 for $11B. $80B+ digital infrastructure AUM.'),
  ('x_life360', 'Life360/Tile', 'Corporation', 'Hubble 90M+ device partner'),
  ('x_mgm', 'MGM Resorts', 'Corporation', 'PlayStudios rewards partner + ~10% equity stake via PIPE. Exclusive social gaming rights.'),
  ('x_marriott', 'Marriott', 'Corporation', 'PlayStudios rewards'),
  ('x_muonspace', 'Muon Space', 'Corporation', 'Hubble satellite bus contract'),
  ('x_unr', 'UNR', 'University', 'Research partnerships'),
  ('x_ssbci', 'NV SSBCI', 'Government', 'Fund matching program'),
  ('x_caesars', 'Caesars Entertainment', 'Corporation', 'Co-founded Black Fire Innovation with UNLV 2020. Zero Labs advisor.'),
  ('x_panasonic', 'Panasonic', 'Corporation', 'Black Fire tech partner.'),
  ('x_boyd', 'Boyd Gaming', 'Corporation', 'LV-based casino operator. Boyd Innovation Lab at Black Fire Innovation (2023).'),
  ('x_intel', 'Intel', 'Corporation', 'Key computing partner at Black Fire Innovation.'),
  ('x_shift', 'Shift Studio', 'Corporation', 'Innovation/product studio. $300K strategic partnership with Zero Labs.'),
  ('x_usaf', 'US Air Force', 'Government', 'AFWERX parent organization'),
  ('x_accel', 'Accel', 'VC Firm', 'Led Socure Series D/E. $450M round.'),
  ('x_trowe', 'T. Rowe Price', 'VC Firm', 'Co-led Socure Series E $450M'),
  ('x_tiger', 'Tiger Global', 'VC Firm', 'Socure Series E investor'),
  ('x_wellington', 'Wellington Mgmt', 'VC Firm', 'Led Abnormal AI Series D $250M at $5.1B'),
  ('x_greylock', 'Greylock', 'VC Firm', 'Abnormal AI investor since inception'),
  ('x_insight', 'Insight Partners', 'VC Firm', 'Abnormal AI Series C/D'),
  ('x_crowdstrike', 'CrowdStrike', 'Corporation', 'CrowdStrike Falcon Fund -> Abnormal AI'),
  ('x_amd', 'AMD Ventures', 'Corporation', 'Co-led TensorWave Series A. Strategic GPU partner.'),
  ('x_magnetar', 'Magnetar', 'VC Firm', 'Co-led TensorWave $100M Series A'),
  ('x_nexusvp', 'Nexus Venture Partners', 'VC Firm', 'Led TensorWave $43M SAFE round'),
  ('x_blackrock', 'BlackRock', 'PE Firm', 'Co-led MNTN Series D $119M'),
  ('x_fidelity', 'Fidelity', 'Investment Co', 'Co-led MNTN Series D $119M'),
  ('x_greycroft', 'Greycroft', 'VC Firm', 'Early MNTN investor'),
  ('x_thor', 'THOR Industries', 'Corporation', 'Strategic investor in Dragonfly Energy.'),
  ('x_eip', 'Energy Impact Partners', 'VC Firm', 'Led $75M term loan for Dragonfly SPAC'),
  ('x_draper', 'Draper Associates', 'VC Firm', 'Tim Draper. Boxabl investor.'),
  ('x_bain_cv', 'Bain Capital Ventures', 'VC Firm', 'Socure Series E.'),
  ('x_commerce_v', 'Commerce Ventures', 'VC Firm', 'Socure investor Series B onward.'),
  ('x_sorenson', 'Sorenson Capital', 'VC Firm', 'Socure investor since Series C.'),
  ('x_twosigma', 'Two Sigma Ventures', 'VC Firm', 'Socure Series A investor.'),
  ('x_citi_v', 'Citi Ventures', 'Corporation', 'Strategic investor in Socure.'),
  ('x_cap1_v', 'Capital One Ventures', 'Corporation', 'Strategic investor in Socure.'),
  ('x_menlo', 'Menlo Ventures', 'VC Firm', 'Abnormal AI Series B/C/D.'),
  ('x_evolution', 'Evolution Equity', 'VC Firm', 'Led Protect AI Series A+B.'),
  ('x_salesforce_v', 'Salesforce Ventures', 'Corporation', 'Protect AI Series A/B.'),
  ('x_pelion', 'Pelion Ventures', 'VC Firm', 'Protect AI seed->B.'),
  ('x_boldstart', 'Boldstart Ventures', 'VC Firm', 'Protect AI seed->B.'),
  ('x_samsung', 'Samsung', 'Corporation', 'Protect AI Series B.'),
  ('x_paloalto', 'Palo Alto Networks', 'Corporation', 'Acquired Protect AI Apr 2025.'),
  ('x_prosperity7', 'Prosperity7', 'VC Firm', 'Aramco Ventures. TensorWave Series A.'),
  ('x_maverick', 'Maverick Silicon', 'VC Firm', 'TensorWave SAFE+A.'),
  ('x_translink', 'TransLink Capital', 'VC Firm', 'TensorWave SAFE.'),
  ('x_mercato', 'Mercato Partners', 'VC Firm', 'MNTN early investor.'),
  ('x_qualcomm_v', 'Qualcomm Ventures', 'Corporation', 'MNTN early investor.'),
  ('x_rincon', 'Rincon Venture Partners', 'VC Firm', 'MNTN early investor.'),
  ('x_baroda', 'Baroda Ventures', 'VC Firm', 'MNTN early investor.'),
  ('x_buildtech', 'BuildTech VC', 'VC Firm', 'Boxabl investor.'),
  ('x_elevation', 'Elevation Capital', 'VC Firm', 'Boxabl investor.'),
  ('x_chardan', 'Chardan Capital', 'VC Firm', 'Dragonfly SPAC sponsor.'),
  ('x_warburg', 'Warburg Pincus', 'PE Firm', 'Led Duetto Series D $80M.'),
  ('x_battery', 'Battery Ventures', 'VC Firm', 'Led Duetto Series A $10M.'),
  ('x_growthcurve', 'GrowthCurve Capital', 'PE Firm', 'Acquired Duetto Jun 2024.'),
  ('x_blackstone', 'Blackstone', 'PE Firm', 'Led Carbon Health Series D $350M.'),
  ('x_cvs', 'CVS Health Ventures', 'Corporation', 'Led Carbon Health Series D2 $100M.'),
  ('x_dragoneer', 'Dragoneer Investment Group', 'VC Firm', 'Led Carbon Health Series C $100M.'),
  ('x_lightspeed', 'Lightspeed Venture Partners', 'VC Firm', 'Led 1047 Games Series B $100M.'),
  ('x_galaxy', 'Galaxy Interactive', 'VC Firm', 'Led 1047 Games seed $6.5M.'),
  ('x_apollo', 'Apollo Global Management', 'PE Firm', '$671B AUM. Acquired Everi+IGT Gaming Jul 2025.'),
  ('x_segasammy', 'SEGA SAMMY Holdings', 'Corporation', 'Acquired GAN Limited May 2025.'),
  ('x_orix', 'ORIX Corp', 'Corporation', 'Japanese financial services. Ormat Industries owns 44.76% of Ormat Technologies.'),
  ('x_acuren', 'Acuren', 'Corporation', 'Acquired NV5 Global Aug 2025.'),
  ('x_canaan', 'Canaan Partners', 'VC Firm', 'Led Ollie Series A $12.6M Aug 2017.'),
  ('x_lererhippeau', 'Lerer Hippeau', 'VC Firm', 'Ollie seed co-lead.'),
  ('x_twobear', 'Two Bear Capital', 'VC Firm', 'Led CIQ Series A $26M May 2022.'),
  ('x_iag', 'IAG Capital Partners', 'VC Firm', 'CIQ bridge round 2021.'),
  ('x_tuatara', 'Tuatara Capital', 'VC Firm', 'Springbig SPAC sponsor.'),
  ('x_tvc', 'TVC Capital', 'VC Firm', 'Springbig PIPE investor.'),
  ('x_agrolimen', 'Agrolimen', 'Corporation', 'Spanish conglomerate. Acquired Ollie 2025.'),
  ('x_google', 'Google', 'Corporation', 'Rocky Linux CIQ partner. 150MW geothermal PPA with Ormat.'),
  ('x_ballistic', 'Ballistic Ventures', 'VC Firm', 'Nudge Security seed $7M Apr 2022.'),
  ('x_cerberus_v', 'Cerberus Ventures', 'VC Firm', 'Led Nudge Security Series A $22.5M Nov 2025.'),
  ('x_forgepoint', 'Forgepoint Capital', 'VC Firm', 'Nudge Security seed + Series A.'),
  ('x_squadra', 'Squadra Ventures', 'VC Firm', 'Nudge Security investor.'),
  ('x_efung', 'EFung Capital', 'VC Firm', 'Elicio Therapeutics Series B investor.'),
  ('x_clal_bio', 'Clal Biotechnology', 'Investment Co', 'Elicio Series B.'),
  ('x_eif', 'Ecosystem Integrity Fund', 'VC Firm', 'Led Vibrant Planet seed+Series A.'),
  ('x_msft_climate', 'Microsoft Climate Fund', 'Corporation', 'Vibrant Planet Series A.'),
  ('x_dayonev', 'Day One Ventures', 'VC Firm', 'Vibrant Planet Series A.'),
  ('x_grantham', 'Grantham Foundation', 'Foundation', 'Vibrant Planet seed.'),
  ('x_owl', 'Owl Ventures', 'VC Firm', '$2.2B+ AUM EdTech-focused VC. Amira Learning investor.'),
  ('x_authentic', 'Authentic Ventures', 'VC Firm', 'Led Amira Learning Series A $11M.'),
  ('x_amazon_af', 'Amazon Alexa Fund', 'Corporation', 'Amira Learning investor.'),
  ('x_edf', 'EDF Renewables', 'Corporation', 'Nuvve Series A investor. V2G JV partner (DREEV).'),
  ('x_toyota_tsusho', 'Toyota Tsusho', 'Corporation', 'Nuvve Series A investor Dec 2017.'),
  ('x_newborn', 'Newborn Acquisition', 'SPAC', 'Merged with Nuvve Mar 2021.'),
  ('x_thirdprime', 'Third Prime', 'VC Firm', 'Co-led Climb Credit Series A $9.8M.'),
  ('x_newmarkets', 'New Markets VP', 'VC Firm', 'Co-led Climb Credit Series A.'),
  ('x_newfund', 'Newfund Capital', 'VC Firm', 'Early Climb Credit investor.'),
  ('x_goldman', 'Goldman Sachs AM', 'PE Firm', 'Co-led Redwood Materials Series D $1B.'),
  ('x_capricorn', 'Capricorn Technology Impact', 'VC Firm', 'Co-led Redwood Series D.'),
  ('x_eclipse_v', 'Eclipse Ventures', 'VC Firm', 'Led Redwood Materials Series E $350M Oct 2025.'),
  ('x_nventures', 'NVentures (Nvidia)', 'Corporation', 'Nvidia VC arm. Redwood Materials Series E Oct 2025.'),
  ('x_cpp', 'CPP Investments', 'PE Firm', 'Canada Pension Plan. Redwood Materials Series C.'),
  ('x_breakthrough', 'Breakthrough Energy', 'VC Firm', 'Bill Gates-led climate fund. Redwood Materials Series B.'),
  ('x_amazon_cpf', 'Amazon Climate Pledge', 'Corporation', 'Redwood Materials investor.'),
  ('x_omers', 'OMERS', 'PE Firm', 'Ontario pension. Redwood Materials Series D.'),
  ('x_ford', 'Ford Motor Company', 'Corporation', 'Redwood Materials strategic investor.'),
  ('x_caterpillar_v', 'Caterpillar Ventures', 'Corporation', 'Redwood Materials Series D.'),
  ('x_ozmen', 'Ozmen Ventures', 'VC Firm', 'Eren & Fatih Ozmen family office. SNC owners.'),
  ('x_blueorigin', 'Blue Origin', 'Corporation', 'Orbital Reef partner with Sierra Space.'),
  ('x_swagar', 'Swagar Capital', 'VC Firm', 'Led Hubble Network Series B $70M.'),
  ('x_rpm', 'RPM Ventures', 'VC Firm', 'Hubble Network Series B.'),
  ('x_yc', 'Y Combinator', 'VC Firm', 'Hubble Network Series B investor.'),
  ('x_seraph', 'Seraph Group', 'VC Firm', 'Hubble Network Series B.'),
  ('x_neuberger', 'Neuberger Berman', 'PE Firm', 'PlayStudios PIPE investor.'),
  ('x_clearbridge', 'ClearBridge Investments', 'PE Firm', 'PlayStudios PIPE investor.'),
  ('x_acies', 'Acies Acquisition Corp', 'SPAC', 'PlayStudios SPAC merger Jun 2021.'),
  ('x_stryten', 'Stryten Energy', 'Corporation', '$30M licensing deal for Battle Born Batteries brand.'),
  ('x_6kenergy', '6K Energy', 'Corporation', 'Supply agreement with Aqua Metals.'),
  ('x_goed', 'NV GOED', 'Government', 'Nevada Governor''s Office of Economic Development.'),
  ('x_sibanye', 'Sibanye-Stillwater', 'Corporation', 'Had $490M JV with Ioneer, withdrew Feb 2025.'),
  ('x_fimi', 'FIMI Opportunity Funds', 'PE Firm', 'Ormat''s largest shareholder ~14.8%.'),
  ('x_nvenergy', 'NV Energy', 'Corporation', 'Nevada utility (Berkshire Hathaway Energy).'),
  ('x_goff', 'Goff Capital Partners', 'PE Firm', 'Acquired Canyon Ranch 2017.'),
  ('x_vici', 'VICI Properties', 'PE Firm', '$500M partnership with Canyon Ranch.'),
  ('x_atw', 'ATW Partners', 'VC Firm', 'Kaptyn Series A/B investor.'),
  ('x_kibble', 'Kibble Holdings', 'VC Firm', 'Kaptyn early investor.'),
  ('x_linico', 'LiNiCo Corp', 'Corporation', 'Lithium-ion battery recycler. 64% owned by Comstock.'),
  ('x_marathon', 'Marathon Petroleum', 'Corporation', 'Comstock Fuels strategic investor.'),
  ('x_rwe', 'RWE Clean Energy', 'Corporation', 'Comstock Metals recycling partner.'),
  ('x_igt', 'IGT Gaming', 'Corporation', 'Combined with Everi under Apollo ownership Jul 2025.')
ON CONFLICT (id) DO NOTHING;

-- ── Accelerators ───────────────────────────────────────────────────────────
INSERT INTO accelerators (id, name, accel_type, city, region, founded, note) VALUES
  ('a_startupnv', 'StartUpNV', 'Accelerator/Incubator', 'Las Vegas', 'las_vegas', 2017, 'NV statewide accelerator. Non-cohort. Min $100K via FundNV.'),
  ('a_angelnv', 'AngelNV', 'Angel Program', 'Las Vegas', 'las_vegas', 2019, 'Annual angel investor bootcamp + pitch competition. $200K+ investments.'),
  ('a_adamshub', 'Adams Hub', 'Accelerator', 'Carson City', 'reno', 2020, 'Carson City accelerator.'),
  ('a_gener8tor_lv', 'gener8tor Las Vegas', 'Accelerator', 'Las Vegas', 'las_vegas', 2022, 'SSBCI-funded Battle Born Growth accelerator. 12-week, $100K/company.'),
  ('a_gener8tor_reno', 'gener8tor Reno-Tahoe', 'Accelerator', 'Reno', 'reno', 2022, 'SSBCI-funded at UNR Innevation Center.'),
  ('a_gbeta_nv', 'gBETA Electrify Nevada', 'Pre-Accelerator', 'Las Vegas', 'las_vegas', 2024, 'Free 7-week pre-accelerator by gener8tor.'),
  ('a_innevator', 'InNEVator', 'Pre-Accelerator', 'Reno', 'reno', 2017, '8-week bootcamp at UNR Innevation Center.'),
  ('a_blackfire', 'Black Fire Innovation', 'Incubator/Lab', 'Las Vegas', 'las_vegas', 2020, 'UNLV + Caesars 43K sq ft gaming/hospitality living lab. Harry Reid Tech Park.'),
  ('a_dtp', 'Downtown Project (DTP)', 'Incubator/Fund', 'Las Vegas', 'las_vegas', 2012, 'Tony Hsieh initiative.'),
  ('a_afwerx', 'AFWERX', 'Military Accelerator', 'Las Vegas', 'las_vegas', 2017, 'US Air Force innovation hub. Nellis AFB.'),
  ('a_audacity', 'Audacity Institute', 'Accelerator', 'Reno', 'reno', 2020, 'Inclusive economy focus. TEQSpring program.'),
  ('a_zerolabs', 'Zero Labs', 'Accelerator', 'Las Vegas', 'las_vegas', 2020, 'LV''s first dedicated gaming/hospitality/sports accelerator. 76+ startups supported.')
ON CONFLICT (id) DO NOTHING;

-- ── Ecosystem Orgs ─────────────────────────────────────────────────────────
INSERT INTO ecosystem_orgs (id, name, entity_type, city, region, note) VALUES
  ('e_goed', 'NV GOED', 'Government', 'Carson City', 'reno', 'Governor''s Office of Economic Development. Manages SSBCI, Knowledge Fund.'),
  ('e_edawn', 'EDAWN', 'Economic Development', 'Reno', 'reno', 'Economic Development Authority of Western Nevada.'),
  ('e_lvgea', 'LVGEA', 'Economic Development', 'Las Vegas', 'las_vegas', 'Las Vegas Global Economic Alliance.'),
  ('e_innevation', 'UNR Innevation Center', 'University Hub', 'Reno', 'reno', 'UNR coworking/incubator.'),
  ('e_unlvtech', 'UNLV Tech Park', 'University Hub', 'Las Vegas', 'las_vegas', 'Harry Reid Research & Technology Park. 122 acres.')
ON CONFLICT (id) DO NOTHING;

-- ── Listings (public market companies) ─────────────────────────────────────
INSERT INTO listings (company_id, exchange, ticker) VALUES
  (12, 'Nasdaq', 'SBIG'),
  (27, 'Nasdaq', 'MYPS'),
  (28, 'NYSE', 'EVRI'),
  (33, 'NYSE', 'LODE'),
  (49, 'ASX', 'INR'),
  (50, 'Nasdaq', 'DFLI'),
  (54, 'Nasdaq', 'GAN'),
  (55, 'Nasdaq', 'NXGL'),
  (65, 'Nasdaq', 'SSNT'),
  (67, 'OTC', 'PLNHF'),
  (71, 'TSX', 'JP'),
  (73, 'NYSE', 'AQMS'),
  (74, 'NYSE', 'ORA'),
  (75, 'Nasdaq', 'NVEE'),
  (26, 'Nasdaq', 'DAIC')
ON CONFLICT (company_id, exchange) DO NOTHING;

COMMIT;
